apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "helm.fullname" . }}
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "helm.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "helm.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "helm.selectorLabels" . | nindent 8 }}
        date: "{{ now | unixEpoch }}"
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          securityContext:
            {{- toYaml .Values.security.application.securityContext | nindent 12 }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          {{- if .Values.probes -}}
          {{- toYaml .Values.probes | nindent 10 }}
          {{- end }}
          ports:
            - name: https
              containerPort: {{ .Values.service.appPort }}
              protocol: TCP
          env:
            {{- toYaml .Values.env.application | nindent 10 }}
        - name: proxy
          image: {{ .Values.image.proxyRepository }}
          imagePullPolicy: Always
          securityContext:
            {{- toYaml .Values.security.application.securityContext | nindent 12 }}
          env:
            {{- toYaml .Values.env.proxy | nindent 10 }}
          ports:
            - name: https
              containerPort: {{ .Values.service.targetPort }}
          volumeMounts:
          - name: certs
            mountPath: /certs
      volumes:
        - name: certs
          secret:
            secretName: {{ .Chart.Name }}-pod-cmio
